version: '3.6'
services:
  discordbot:
    restart: unless-stopped
    build:
      context: src
      dockerfile: Dockerfile
    image: hazardous-killbot:latest
    environment:
      DISCORD_BOT_TOKEN: ${DISCORD_BOT_TOKEN}
      DISCORD_CLIENT_ID: ${DISCORD_CLIENT_ID}
      QUEUE_IDENTIFIER: ${QUEUE_IDENTIFIER}
    volumes:
      - ./config:/workspace/dist/config:delegated
    ports:
      - "127.0.0.1:4000:4000"

  mongodb:
    image: mongo:7.0.8
    volumes:
      - ./mongo-data:/data/db
    ports:
      - "127.0.0.1:27017:27017"

networks:
  default:
    name: bot-network
    driver: bridge
